spring.application.name=CustomerService
server.port=8081
spring.datasource.url=jdbc:h2:file:./CustomerService/data/customers;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=h2user1
spring.datasource.password=h2pass1

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true