spring.application.name=RestaurantService
server.port=8082
spring.datasource.url=jdbc:h2:file:./RestaurantService/data/restaurants;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=h2user2
spring.datasource.password=h2pass2

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true